# TCL File Generated by Component Editor 22.1
# Mon Apr 08 14:19:32 MSK 2024
# DO NOT MODIFY


# 
# Count250000 "Count250000" v1.0
#  2024.04.08.14:19:32
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Count250000
# 
set_module_property DESCRIPTION ""
set_module_property NAME Count250000
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Count250000
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Count250000
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Count250000.vhd VHDL PATH components/Count250000.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clkIn
# 
add_interface clkIn clock end
set_interface_property clkIn clockRate 0
set_interface_property clkIn ENABLED true
set_interface_property clkIn EXPORT_OF ""
set_interface_property clkIn PORT_NAME_MAP ""
set_interface_property clkIn CMSIS_SVD_VARIABLES ""
set_interface_property clkIn SVD_ADDRESS_GROUP ""

add_interface_port clkIn clkIn clk Input 1


# 
# connection point clkOut
# 
add_interface clkOut clock start
set_interface_property clkOut associatedDirectClock ""
set_interface_property clkOut clockRate 0
set_interface_property clkOut clockRateKnown false
set_interface_property clkOut ENABLED true
set_interface_property clkOut EXPORT_OF ""
set_interface_property clkOut PORT_NAME_MAP ""
set_interface_property clkOut CMSIS_SVD_VARIABLES ""
set_interface_property clkOut SVD_ADDRESS_GROUP ""

add_interface_port clkOut clkOut clk Output 1

