# TCL File Generated by Component Editor 22.1
# Fri Apr 05 16:20:37 MSK 2024
# DO NOT MODIFY


# 
# DigitalFilter "DigitalFilter" v1.0
#  2024.04.05.16:20:37
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DigitalFilter
# 
set_module_property DESCRIPTION ""
set_module_property NAME DigitalFilter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME DigitalFilter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DigitalFilter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DigitalFilter.vhd VHDL PATH components/DigitalFilter.vhd {CONTAINS_INLINE_CONFIGURATION TOP_LEVEL_FILE}


# 
# parameters
# 
add_parameter PHASE_SHIFT INTEGER 2000 ""
set_parameter_property PHASE_SHIFT DEFAULT_VALUE 2000
set_parameter_property PHASE_SHIFT DISPLAY_NAME PHASE_SHIFT
set_parameter_property PHASE_SHIFT TYPE INTEGER
set_parameter_property PHASE_SHIFT UNITS None
set_parameter_property PHASE_SHIFT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PHASE_SHIFT DESCRIPTION ""
set_parameter_property PHASE_SHIFT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point output0
# 
add_interface output0 conduit end
set_interface_property output0 associatedClock clock
set_interface_property output0 associatedReset ""
set_interface_property output0 ENABLED true
set_interface_property output0 EXPORT_OF ""
set_interface_property output0 PORT_NAME_MAP ""
set_interface_property output0 CMSIS_SVD_VARIABLES ""
set_interface_property output0 SVD_ADDRESS_GROUP ""

add_interface_port output0 output0 key1 Output 1


# 
# connection point input0
# 
add_interface input0 conduit end
set_interface_property input0 associatedClock clock
set_interface_property input0 associatedReset ""
set_interface_property input0 ENABLED true
set_interface_property input0 EXPORT_OF ""
set_interface_property input0 PORT_NAME_MAP ""
set_interface_property input0 CMSIS_SVD_VARIABLES ""
set_interface_property input0 SVD_ADDRESS_GROUP ""

add_interface_port input0 input0 input0 Input 1

